### ISSUE TITLE
Week1 assignment2 instruction  not clearly on coursera website

### ISSUE THREAD

**Issue by 123zmz123** [cu-ecen-aeld/aesd-assignments#12]
on coursera
week1 assignment2 instruction doc recommend you set up ssh connection and generate key pair first.
then it instruct you 
```
git remote add origin < url >
```
**But!** once you configure the ssh, the < url > were not just you repository https address anymore.
instead you need change from
```
origin	https://github.com/cu-ecen-aeld/assignment-2-123zmz123 (fetch)
origin	https://github.com/cu-ecen-aeld/assignment-2-123zmz123 (push)

```

to 
```
origin	git@github.com:cu-ecen-aeld/assignment-2-123zmz123.git (fetch)
origin	git@github.com:cu-ecen-aeld/assignment-2-123zmz123.git (push)

```
at my pc I can not push success  when I use https address. (it report (fatal: Authentication failed for 'https://github.com/cu-ecen-aeld/assignment-2-123zmz123/'))

seems like instruction doc on coursera were not very clear.

**Comment by dwalkes** [comment]
Hi @123zmz123 thanks for the feedback.  I've updated the assignment 2 instructions to reference https://github.com/cu-ecen-aeld/aesd-assignments/wiki/Setting-up-SSH-Access-To-your-Repo
