### ISSUE TITLE
Week 1 Assignment 2, Unable to install ARM aarch64 developer toolchain

### ISSUE THREAD

**Issue by justinjunghkim** [cu-ecen-aeld/aesd-assignments#37]
I spent several days installing the toolchain for the assignment 2. I haven't been successful until now. However, at least I understand what is the problem now. 

I followed through the installation instruction from the release note (Version 10.2-2020.11, "https://developer.arm.com/downloads/-/gnu-a" )

The problem was, when the program checkout dejagnu using manifest file during the installation, the url link associated with dejagnu does not exist. When I opened up a link it it said "no repositories found".

[This link ](https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-a/10.2-2020.11/manifest/gcc-arm-aarch64-none-linux-gnu-abe-manifest.txt
)is the manifest text file. 

The url from the manifest.txt file for dejagnu I found is below.
dejagnu_url=http://git.linaro.org/git/toolchain

I'm very new to Linux, so maybe someone with prior experience knows what to do in this situation as many people seemed to move on from assignment 2. However, I found it very frustrating. 

Please advise.

I attached the screenshot of error message. 
![error_msg](https://github.com/cu-ecen-aeld/aesd-assignments/assets/72030332/5dfcad1d-91f1-42c0-a084-478d1131ea0d)

**Comment by dwalkes** [comment]
Hi @justinjunghkim sorry for the frustration.

I suspect you didn't see the link to the instructions at https://github.com/cu-ecen-aeld/aesd-assignments/wiki/Installing-an-ARM-aarch64-developer-toolchain referenced in the assignment 2 implementation step 2?

Or perhaps you did and you didn't find the "Installation Instructions" referenced there in the README.  Those are the ones you need to follow.

![image](https://github.com/user-attachments/assets/ddeaeb19-854d-45f6-a72e-19e601046421)
