### ISSUE TITLE
Confusing instructions for github

### ISSUE THREAD

**Issue by saharmdu** [cu-ecen-aeld/aesd-assignments#40]
Hi,
I am new to Linux and haven't used GitHub professionally before. By following the lectures, the assignments are solvable. However, my main issue so far has been working with GitHub! Please provide simple, step-by-step instructions for using GitHub in assignments. All the instructions we have are just linking several pages to each other. It is very difficult to follow since all steps have other requirements.

**Comment by dwalkes** [comment]
Hi @saharmdu thanks for the feedback.  I attempt to provide step by step instructions for the most complicated steps but I think it might be challenging to cover every possible step in the assignment document.  I suggest the github guides like https://docs.github.com/en/get-started/start-your-journey/hello-world as a starting point if you haven't used git previously and would like more background before attempting assignments.
