### ISSUE TITLE
Settings option is missing for aesd-assignments repo

### ISSUE THREAD

**Issue by GirishH** [cu-ecen-aeld/aesd-assignments#42]
Under section for "setting up self hosted runners" there is reference to a "Settings" tab for the repository. 
This "Settings" tab is not visible by default, the documentation alludes to this scenario but there is no ".." drop down list present on code repository page.
Can somebody help?
I'm using Chrome browser on development host and Fedora browser on the guest Ubuntu 20.04 VM hosted by Virtual box.

**Comment by dwalkes** [comment]
Hi @GirishH you need to create your own repository using the instructions and github classroom, you won't be able to access settings on this repository.
